project:
  type: website

website:
  title: "Blog de Ciencia de Datos e IA"
  site-url: https://JAles83.github.io
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre mí
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



